# Form implementation generated from reading ui file 'dlgAdmin.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAdmin(object):
    def setupUi(self, dlgAdmin):
        dlgAdmin.setObjectName("dlgAdmin")
        dlgAdmin.resize(367, 322)
        dlgAdmin.setStyleSheet("#dlgAdmin {background-color: rgb(221, 99, 127)}")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=dlgAdmin)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 361, 301))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lblTitle = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.lblTitle.setMinimumSize(QtCore.QSize(180, 0))
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lblTitle.setStyleSheet("#lblTitle {background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.085 rgba(2, 79, 0, 255), stop:0.19 rgba(50, 147, 22, 255), stop:0.275 rgba(236, 191, 49, 255), stop:0.39 rgba(243, 61, 34, 255), stop:0.555 rgba(135, 81, 60, 255), stop:0.667 rgba(121, 75, 255, 255), stop:0.825 rgba(164, 255, 244, 255), stop:0.885 rgba(104, 222, 71, 255), stop:1 rgba(93, 128, 0, 255))}")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout_4.addWidget(self.lblTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.labelAdmin = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.labelAdmin.setMinimumSize(QtCore.QSize(0, 0))
        self.labelAdmin.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Script MT")
        font.setPointSize(16)
        font.setBold(True)
        self.labelAdmin.setFont(font)
        self.labelAdmin.setStyleSheet("#labelAdmin {color : red; background-color: rgb(228, 234, 206)}")
        self.labelAdmin.setObjectName("labelAdmin")
        self.horizontalLayout_5.addWidget(self.labelAdmin)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btnAddUser = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnAddUser.setFont(font)
        self.btnAddUser.setStyleSheet("#btnAddUser {background-color:rgb(61, 187, 255);\n"
"color: white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:4px;\n"
"border-color:rgb(255, 255, 0);\n"
"padding:5px;}")
        self.btnAddUser.setObjectName("btnAddUser")
        self.horizontalLayout.addWidget(self.btnAddUser)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.btnChangePassword = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnChangePassword.setFont(font)
        self.btnChangePassword.setStyleSheet("#btnChangePassword {background-color:rgb(61, 187, 255);\n"
"color: white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:4px;\n"
"border-color:rgb(255, 255, 0);\n"
"padding:5px;}")
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.horizontalLayout_2.addWidget(self.btnChangePassword)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.btnOops = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOops.setFont(font)
        self.btnOops.setStyleSheet("#btnOops {background-color:rgb(61, 187, 255);\n"
"color: white;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:4px;\n"
"border-color:rgb(255, 255, 0);\n"
"padding:5px;}")
        self.btnOops.setObjectName("btnOops")
        self.horizontalLayout_3.addWidget(self.btnOops)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.verticalLayoutWidget_2)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(dlgAdmin)
        self.buttonBox.accepted.connect(dlgAdmin.accept) # type: ignore
        self.buttonBox.rejected.connect(dlgAdmin.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgAdmin)

    def retranslateUi(self, dlgAdmin):
        _translate = QtCore.QCoreApplication.translate
        dlgAdmin.setWindowTitle(_translate("dlgAdmin", "Dialog"))
        self.lblTitle.setText(_translate("dlgAdmin", "<html><head/><body><p><span style=\" font-size:16pt;\">StorageToo</span></p></body></html>"))
        self.labelAdmin.setText(_translate("dlgAdmin", "Administrator"))
        self.btnAddUser.setText(_translate("dlgAdmin", "Add User"))
        self.btnChangePassword.setText(_translate("dlgAdmin", "Change Password"))
        self.btnOops.setText(_translate("dlgAdmin", "Delete User"))
